/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

#define DEL_PROG 0x20000076
#define DEL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DEL 1
extern  char * del_1(nametype *, CLIENT *);
extern  char * del_1_svc(nametype *, struct svc_req *);
extern int del_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DEL 1
extern  char * del_1();
extern  char * del_1_svc();
extern int del_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);

#else /* K&R C */
extern bool_t xdr_nametype ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
