/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"





int
main (int argc, char *argv[])
{
	char *host;
	char *path;


	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	path= argv[2];

	CLIENT *clnt;
	char  *result_1;
	
	clnt = clnt_create (host, DEL_PROG, DEL_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = del_1(&path, clnt);
	if (result_1 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
exit (0);
}
