/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

char * del_1_svc(nametype *argp, struct svc_req *rqstp)
{
	static char  result;

	int i, len;
    
    char *str= malloc((50)*(sizeof(char)));
    sprintf(str, "sudo rm -rf ");
    strcat(str, *argp);
    i= system(str);
    if(i== -1)
    	result= 'n';
    result= 'y';

	return (&result);
}
