/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RENAME_H_RPCGEN
#define _RENAME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

struct name {
	nametype old;
	nametype final;
};
typedef struct name name;

#define RENAME_PROG 0x20000076
#define RENAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RENAME 1
extern  char * rename_1(name *, CLIENT *);
extern  char * rename_1_svc(name *, struct svc_req *);
extern int rename_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RENAME 1
extern  char * rename_1();
extern  char * rename_1_svc();
extern int rename_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_name (XDR *, name*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_name ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RENAME_H_RPCGEN */
