/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "move.h"

char *
move_1_svc(name *argp, struct svc_req *rqstp)
{
	static char  result;
	int i;
    char *str= malloc((100)*(sizeof(char)));
    sprintf(str, "sudo mv ");
    strcat(str, argp->old);
    strcat(str," ");
    strcat(str, argp->final);
    i= system(str);
    printf("%s",str);
    if(i== -1)
    	result= 'n';
    result= 'y';

	return &result;
}
